# Automapper configuration
# [templates.example_template] - example_template should be replaced with the name of your map template.
# directory - The direct path to our map files.
# map_files - These are the names of the map files, including the extension, that will be loaded. Supports multiple for randomness.
# required_map - This is the name of the required map that needs to be loaded in order for this template to load.
# coordinates - The coordinates of the map template placement. (X, Y, Z). PLEASE NOTE: The Z coordinate is the same as would be shown in SDMM. NOT IN GAME.
# leave it at 1 if it is not a multi-z map. It is relative to the map file Z, not the one loaded in game.
# trait_name - The name of the Z level trait that will be used to determine what Z level we use.
# Traits - Station (for station relatied edits), CentCom (for edits on the CC map), Mining (for edits on Lavaland)
# More can be found in code\__DEFINES\maps.dm

# Metastation Cryo
# [templates.metastation_cryo]
# map_files = ["metastation_cryo.dmm"]
# directory = "_maps/bandastation/automapper/templates/metastation/"
# required_map = "MetaStation.dmm"
# coordinates = [133, 182, 1]
# trait_name = "Station"

# Metastation Job Display System
[templates.metastation_job_display_system]
map_files = ["metastation_job_display_system.dmm"]
directory = "_maps/bandastation/automapper/templates/metastation/"
required_map = "MetaStation.dmm"
coordinates = [210, 126, 1]
trait_name = "Station"

# Deltastation Job Display System
[templates.deltastation_job_display_system]
map_files = ["deltastation_job_display_system.dmm"]
directory = "_maps/bandastation/automapper/templates/deltastation/"
required_map = "DeltaStation2.dmm"
coordinates = [152, 127, 1]
trait_name = "Station"

# Birdshot Job Display System
[templates.birdshot_job_display_system]
map_files = ["birdshot_job_display_system.dmm"]
directory = "_maps/bandastation/automapper/templates/birdshot/"
required_map = "birdshot.dmm"
coordinates = [184, 95, 1]
trait_name = "Station"

# IceBoxStation Job Display System
[templates.iceboxstation_job_display_system]
map_files = ["iceboxstation_job_display_system.dmm"]
directory = "_maps/bandastation/automapper/templates/iceboxstation/"
required_map = "IceBoxStation.dmm"
coordinates = [101, 89, 3]
trait_name = "Station"

# TramStation Job Display System
[templates.tramstation_job_display_system]
map_files = ["tramstation_job_display_system.dmm"]
directory = "_maps/bandastation/automapper/templates/tramstation/"
required_map = "tramstation.dmm"
coordinates = [101, 90, 1]
trait_name = "Station"
